### PR TITLE
x0ret's code in decompile3 for annotation types

### PR DESCRIPTION
**Pull request by rocky**
Please review to make sure I didn't botch your change. Also I'd be grateful if you would add your test cases.

### CODE REVIEW

**Comment by x0ret** [comment]
I think there should be these lines [L646-L656](https://github.com/rocky/python-decompile3/blob/master/decompyle3/semantics/make_function.py#L646-L656)

I've added test cases to `decompyle3`.

Let me know if you don't have time to fix this.

**Comment by rocky** [comment]
I'd be grateful if you'd add the lines, continue and finish what needs fixing.. Many thanks.

**Comment by x0ret** [comment]
I've just added test cases and complete changes.

Also please merge decompyle3 `annotation-types` branch into master for test cases.

**Comment by rocky** [comment]
I love the tests! Many thanks for handling this.

**Pull request merged**
