### PR TITLE
Test with latest PyPy in Travis

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by rocky** [comment]
I like the idea of testing on Pypy. I looks like right now there is an error using travis though.

I wonder how fragile adding custom code is going to be.

**Comment by thedrow** [comment]
Sorry about the indentation issue. This should run now.

**Comment by rocky** [comment]
It looks like there are two problems, uncovered here. First is the fact on pypy we shouldn't be verifying off of equivalent-version CPython. The second problem looks like there is a legitimate bug in deparsing on PyPy that should be fixed. The offending bytecode file has name `bsddb/dbrecio.pyc`

**Comment by rocky** [comment]
Merged by accident - meant to keep this open.

**Pull request merged**
