### PR TITLE
Fix py3 function signatures + annotations + ordering

### LINKED ISSUE #258: 3.3-6 function signature with *
```
class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(*, a:float, b:str, c:str = 'test', **kwargs: int) -> int:
            pass
```
on 3.3-3.4 gives: 

```
class TestSignatureObject:

    def test_signature_on_wkwonly(self):

        def test(*, **b: str) -> int:
            pass
# okay decompiling /tmp/bug-3.3.pyc
```

On 3.6 gives: 

```
class TestSignatureObject:

    def test_signature_on_wkwonly(self):

        def test(*, c='test'**a):
            pass
```

Follow up to #257

### PR DESCRIPTION
**Pull request by x0ret**
Fixes #258, #256.

@rocky, Sorry for previous buggy PRs. This one seems be functional and correct. Please take a look.
Params ordering are captured from `code.co_varnames`.

Tested: 
- Python 3.3
- Python 3.4
- Python 3.5
- Python 3.6

### CODE REVIEW

**Comment by x0ret** [comment]
All of test cases:

```python
class TestSignatureObjectA():
    def test_signature_on_wkwonly(self):
        def test(*, a:float, b:str, c:str = 'test', **kwargs: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(*, c='test', a:float, b:str="S", **kwargs: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(*, c='test', a:float, kwargs:str="S", **b: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(x=55, *args, c:str='test', a:float, kwargs:str="S", **b: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(x=55, *args: int, c='test', a:float, kwargs:str="S", **b: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(x:int=55, *args: (int, str), c='test', a:float, kwargs:str="S", **b: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(c='test', kwargs:str="S", **b: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(**b: int) -> int:
            pass

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(a, **b: int) -> int:
            pass
```

**Comment by x0ret** [comment]
Thank you for the tests, I should try harder in tests, Let me fix 1, 2 for now.

**Comment by x0ret** [comment]
@rocky, python <= 3.2.6 we get this:
```
                     1. kwargs: ('%D', (0, 9223372036854775807, ', '))
                        kwarg (2): ('%[0]{attr}=%c', 1)
                             0.              3  LOAD_STR                 'test'
                             1. expr
                                             6  LOAD_STR                 'kwargs'
                     2. kwargs: ('%D', (0, 9223372036854775807, ', '))
                        kwarg (2): ('%[0]{attr}=%c', 1)
                             0.              9  LOAD_STR                 'S'
                             1. expr
                                            12  LOAD_CONST           55  55
```
for:
```python

class TestSignatureObject():
    def test_signature_on_wkwonly(self):
        def test(x=55, *args, c:str='test', a:float, kwargs:str="S", **b: int) -> int:
            pass
```

Please note the kwargs (1, 2), Something is wrong with `LOAD_STR`s

**Comment by rocky** [comment]
> Please note the kwargs (1, 2), Something is wrong with LOAD_STRs

@x0ret I don't see the problem - please explain in more detail. I am getting 

```
      def test(x=55, *args, c:str='test', a:float, kwargs:str="S", **b: int) -> int:
```

In 3.0 on since I fixed the parsing problem. 

However where I am seeing a problem in 3.0 on is above: 

```
 def test_signature_on_wkwonly(self):
```

comes out: 

```
 def test_signature_on_wkwonly(self, ):
```

**Comment by x0ret** [comment]
> In 3.0 on since I fixed the parsing problem.

This was before your fix, Thanks.

> However where I am seeing a problem in 3.0 on is above:

Oh I'm so sorry. Should be fixed now.

**Comment by rocky** [comment]
@x0ret Almost perfect! One last little thing 3.0 - 3.5 seems to have a trailing comma now: 

For: 
```
    def ann1(args_1, b: 'annotating b', c: int, *varargs: str) -> float:
```

I am getting:

```
    def ann1(args_1, b: 'annotating b', c: int, *varargs: str, ) -> float:
                                                             ^
```

To test on 3.5 I run:

```
python test_pythonlib.py --bytecode-3.5-run --verify-run
```

You'll see:

```
>>Syntax error in /tmp/py-dis-78n65m3r/bytecode_3.5_run/04_def_annotate.py
bytecode_3.5_run/10_mixed_boolean.pyc -- decompiled 11 files: 11 okay, 0 failed, 0 run verification failed
```

And there is a bug that this is not logged as an error. 

Hang in there! Thanks for all the persistent work. Really, it would have been a long long long time were it not for your persistence.

**Comment by rocky** [comment]
@x0ret  Looks like everything passes now! Thanks! 

It occured to me late that, maybe "ends_in_comma" could be removed if we pushed all the parameters onto a list and `, `.join at the end. this might lose line break info though. We can leave that for some other time, if it anyone is interested in pursuing. 

For now though, I'm happy all of this is behind us. We should think about a release now.

**Comment by x0ret** [comment]
> It occured to me late that, maybe "ends_in_comma" could be removed if we pushed all the parameters onto a list and , .join at the end.

I'll check out later.

> For now though, I'm happy all of this is behind us. We should think about a release now.

This is great, Thank you. This couldn't be done without your patience. 
Also i think there should be a release for xdis (unicode issue).

**Pull request merged**
