### PR TITLE
declare Python3 support in wheel and trove

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
you'll need to deploy using `python3 sdist bdist_wheel register upload` now

**Comment by rocky** [comment]
I'm not sure I understand. Right now I run: 

```shell

PYVERSIONS='2.6.9 2.7.8 3.4.2 3.5.0'
# run tests on $PYVERSIONS
for version in $PYVERSIONS; do pyenv local $version && make dist && python setup.py bdist_egg upload; done
for version in $PYVERSIONS; do pyenv local $version && make dist && python setup.py bdist_wheel upload; done

python setup.py sdist upload
```

So what now does this become?

**Comment by graingert** [comment]
PYVERSIONS='2.6.9 2.7.8 3.4.2 3.5.0'
# run tests on $PYVERSIONS
for version in $PYVERSIONS; do pyenv local $version && make dist && python setup.py bdist_egg upload; done

`python setup.py sdist bdist_wheel upload`

**Comment by rocky** [comment]
Ok. Thanks - noted. 

P.S. You might want to star this project so attention is diverted from other uncompyle2's on github.

**Comment by rocky** [comment]
First release with this code done. Check https://pypi.python.org/pypi?name=uncompyle6&version=2.2.0&:action=display to see if this matches what you expect.

**Comment by graingert** [comment]
Looks good. Not sure if you need the eggs anymore though

**Pull request merged**
