### PR TITLE
Docstrings yet again

### PR DESCRIPTION
**Pull request by rocky**
Prefer `"""` over `'''` (I think one of the style guides suggests this). 
Fixes 

```
def dq9():
    """Return filenames for package's data files in 'src_dir'"""
    assert dq9.__doc__ == """Return filenames for package's data files in 'src_dir'"""
```

But note that this was and still is broken:

```
def dq7():
  u"""        <----- SEE 'u' HERE
  >>> mylen(u"áéíóú")
  5
  """
  assert dq7.__doc__ ==   u"""        <----- SEE 'u' HERE
  >>> mylen(u"áéíóú")
  5
  """
```

Note bytecode_3.6 test removed because it is now in bytecode_3.6_run.

### CODE REVIEW

**Comment by rocky** [comment]
Sorry for the noise - this may be an improper merge on my side.

**Comment by x0ret** [comment]
@rocky, what about [docstring-again](https://github.com/rocky/python-uncompyle6/tree/docstrings-again) branch? we had a merge which is not merged to master or in this PR.

**Comment by rocky** [comment]
Ok. Let's try that then... Sorry - I make a lot of mistakes..

**Comment by rocky** [comment]
@x0ret  you are right again. My mistake was closing my PR and not realizing yours was on top of mine (which I appreciate your doing).  So I'll close this one.

**Pull request closed without merging**
